version: '3.8'

services:
  # PostgreSQL with Northwind Database
  postgres:
    image: postgres:15
    container_name: northwind-postgres
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"  # Map to 5433 to avoid conflict with local PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - graphrag-network

  # Neo4j Graph Database
  neo4j:
    image: neo4j:5.15-community
    container_name: graphrag-neo4j
    environment:
      NEO4J_AUTH: neo4j/neo4jpassword
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      # Enable vector indexes (for embeddings)
      NEO4J_db_tx__log_rotation_retention__policy: "1 days"
    ports:
      - "7474:7474"  # HTTP Browser Interface
      - "7687:7687"  # Bolt Protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p neo4jpassword 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - graphrag-network

volumes:
  postgres_data:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local

networks:
  graphrag-network:
    driver: bridge
